/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Skateboard_Designer;

/**
 *
 * @author marlon
 */
public class SkateboardDesignerGUI extends javax.swing.JFrame {
    double[] i = new double [4];

    /**
     * Creates new form SkateboardDesignerGUI
     */
    public SkateboardDesignerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Choose_a_axle = new javax.swing.JComboBox<>();
        Choose_a_wheel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblDeck = new javax.swing.JLabel();
        jlblAxle = new javax.swing.JLabel();
        jlblWheels = new javax.swing.JLabel();
        bearingsBox = new javax.swing.JCheckBox();
        riserpadsBox = new javax.swing.JCheckBox();
        griptapeBox = new javax.swing.JCheckBox();
        nutsboltsBox = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        Choose_a_deck = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        calculate = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jTextField1.setFont(new java.awt.Font("Helvetica Neue", 0, 90)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Skateboard Designer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, 110));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Choose_a_axle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Choose_a_axle.setForeground(new java.awt.Color(0, 0, 0));
        Choose_a_axle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make Selection", "7.75", "8", "8.5" }));
        Choose_a_axle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_a_axleActionPerformed(evt);
            }
        });
        jPanel4.add(Choose_a_axle, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 260, 60));

        Choose_a_wheel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Choose_a_wheel.setForeground(new java.awt.Color(0, 0, 0));
        Choose_a_wheel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make Selection", "51", "55", "58", "61 " }));
        Choose_a_wheel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_a_wheelActionPerformed(evt);
            }
        });
        jPanel4.add(Choose_a_wheel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 260, 60));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Decks");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 17, 400, 70));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Axles (inch's)");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 410, 70));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Wheels  (mm's)");
        jLabel3.setToolTipText("");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 400, 70));

        jlblDeck.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jlblDeck.setForeground(new java.awt.Color(0, 0, 0));
        jlblDeck.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(jlblDeck, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 100, 60));

        jlblAxle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jlblAxle.setForeground(new java.awt.Color(0, 0, 0));
        jlblAxle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(jlblAxle, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 100, 60));

        jlblWheels.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jlblWheels.setForeground(new java.awt.Color(0, 0, 0));
        jlblWheels.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(jlblWheels, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 100, 100, 60));

        bearingsBox.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        bearingsBox.setForeground(new java.awt.Color(0, 0, 0));
        bearingsBox.setText("Bearings $30");
        jPanel4.add(bearingsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 60));

        riserpadsBox.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        riserpadsBox.setForeground(new java.awt.Color(0, 0, 0));
        riserpadsBox.setText("Riser Pads $2");
        jPanel4.add(riserpadsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 240, 60));

        griptapeBox.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        griptapeBox.setForeground(new java.awt.Color(0, 0, 0));
        griptapeBox.setText("Grip Tape $10");
        griptapeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                griptapeBoxActionPerformed(evt);
            }
        });
        jPanel4.add(griptapeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 210, 60));

        nutsboltsBox.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        nutsboltsBox.setForeground(new java.awt.Color(0, 0, 0));
        nutsboltsBox.setText("Nuts & Bolts $3");
        jPanel4.add(nutsboltsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 260, 220, 60));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Additional Add-on's");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 590, 70));

        Choose_a_deck.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Choose_a_deck.setForeground(new java.awt.Color(0, 0, 0));
        Choose_a_deck.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make Selection", "Master Trasher", "Dictator", "Street King" }));
        Choose_a_deck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_a_deckActionPerformed(evt);
            }
        });
        jPanel4.add(Choose_a_deck, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 60));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1350, 330));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calculate.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        jPanel5.add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 360, 160));

        exit.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel5.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, 250, 70));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Subtotal:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 60));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tax:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, 60));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Total:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 230, 60));

        jtxtSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        jtxtSubTotal.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jtxtSubTotal.setForeground(new java.awt.Color(0, 0, 0));
        jtxtSubTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 250, 60));

        jtxtTotal.setBackground(new java.awt.Color(255, 255, 255));
        jtxtTotal.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jtxtTotal.setForeground(new java.awt.Color(0, 0, 0));
        jtxtTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 250, 60));

        jtxtTax.setBackground(new java.awt.Color(255, 255, 255));
        jtxtTax.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jtxtTax.setForeground(new java.awt.Color(0, 0, 0));
        jtxtTax.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 250, 60));

        reset.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel5.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, 250, 70));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 1350, 220));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void griptapeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_griptapeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_griptapeBoxActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        
        double bearing = 30;
        double griptape = 10;
        double riserpads = 2;
        double nutsbolts = 3;
        
        double AddAll;
        double iTax = 7;
        double Tax;
        double Choosen_Deck = Double.parseDouble(jlblDeck.getText());
        double Choosen_Axle = Double.parseDouble(jlblAxle.getText());
        double Choosen_Wheel = Double.parseDouble(jlblWheels.getText());
        
        jtxtSubTotal.setText("");
        jtxtTotal.setText("");
        
        if (Choose_a_deck.getSelectedItem().equals("") && (Choose_a_axle.getSelectedItem().equals("")) 
                        && Choose_a_wheel.getSelectedItem().equals(""));
        {
            if (bearingsBox.isSelected())
                    {
                    Choosen_Deck  = Choosen_Deck + Choosen_Axle + Choosen_Wheel;
                    
                         i[0] = bearing; 
                         i[1] = griptape;
                         i[2] = riserpads;
                         i[3] = nutsbolts;
                         
                        AddAll = Choosen_Deck + i[0];
                        
                        Tax = (AddAll * (iTax/100));
                        String sTax = String.format("$ %.2f", Tax);
                        jtxtTax.setText(sTax);
                    
                        String SubTotal = String.format("$ %.2f", AddAll);
                        jtxtSubTotal.setText(SubTotal);
                    
                        String Total = String.format("$ %.2f", AddAll + Tax);
                        jtxtTotal.setText(Total);
                        }
                    
                    else if (griptapeBox.isSelected())
                    {
                    Choosen_Deck  = Choosen_Deck + Choosen_Axle + Choosen_Wheel;
                    
                         i[0] = bearing; 
                         i[1] = griptape;
                         i[2] = riserpads;
                         i[3] = nutsbolts;
                         
                        AddAll = Choosen_Deck + i[1];
                    
                    
                    
                    Tax = (AddAll * (iTax/100));
                    String sTax = String.format("$ %.2f", Tax);
                    jtxtTax.setText(sTax);
                    
                    String SubTotal = String.format("$ %.2f", AddAll);
                    jtxtSubTotal.setText(SubTotal);
                    
                    String Total = String.format("$ %.2f", AddAll + Tax);
                    jtxtTotal.setText(Total);
                    }
                    else if (riserpadsBox.isSelected())
                    {
                    Choosen_Deck  = Choosen_Deck + Choosen_Axle + Choosen_Wheel;
                    
                         i[0] = bearing; 
                         i[1] = griptape;
                         i[2] = riserpads;
                         i[3] = nutsbolts;
                         
                        AddAll = Choosen_Deck + i[2];
                    
                    
                    
                    Tax = (AddAll * (iTax/100));
                    String sTax = String.format("$ %.2f", Tax);
                    jtxtTax.setText(sTax);
                    
                    String SubTotal = String.format("$ %.2f", AddAll);
                    jtxtSubTotal.setText(SubTotal);
                    
                    String Total = String.format("$ %.2f", AddAll + Tax);
                    jtxtTotal.setText(Total);
                    }
                    
                    else if (nutsboltsBox.isSelected())
                    {
                    Choosen_Deck  = Choosen_Deck + Choosen_Axle + Choosen_Wheel;
                    
                         i[0] = bearing; 
                         i[1] = griptape;
                         i[2] = riserpads;
                         i[3] = nutsbolts;
                         
                        AddAll = Choosen_Deck + i[3];
                    
                    
                    
                    Tax = (AddAll * (iTax/100));
                    String sTax = String.format("$ %.2f", Tax);
                    jtxtTax.setText(sTax);
                    
                    String SubTotal = String.format("$ %.2f", AddAll);
                    jtxtSubTotal.setText(SubTotal);
                    
                    String Total = String.format("$ %.2f", AddAll + Tax);
                    jtxtTotal.setText(Total);
                    }
                       
            else 
            {
                AddAll = Choosen_Deck + Choosen_Axle + Choosen_Wheel;
                String SubTotal = String.format("$ %.2f", AddAll);
                jtxtSubTotal.setText(SubTotal);
                
                Tax = (AddAll * (iTax/100));
                String sTax = String.format("$ %.2f", Tax);
                jtxtTax.setText(sTax);
                
                String Total = String.format("$ %.2f", AddAll + Tax);
                jtxtTotal.setText(Total);
                }
                }
    }//GEN-LAST:event_calculateActionPerformed

    private void Choose_a_deckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_a_deckActionPerformed
        // TODO add your handling code here:
        double trasher = 60;
        double dictator = 45;
        double king = 50;
        
        if (Choose_a_deck.getSelectedItem().equals("Make Selection"))
        {
            jlblDeck.setText(" ");
        }
        if (Choose_a_deck.getSelectedItem().equals("Master Trasher"))
        {
            String Decks = String.format("%.2f", trasher);
            jlblDeck.setText(Decks);
        }
        if (Choose_a_deck.getSelectedItem().equals("Dictator"))
        {
            String Decks = String.format("%.2f", dictator);
            jlblDeck.setText(Decks);
        }
        if (Choose_a_deck.getSelectedItem().equals("Street King"))
        {
            String Decks = String.format("%.2f", king);
            jlblDeck.setText(Decks);
        }
        
        
               
    }//GEN-LAST:event_Choose_a_deckActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        jlblDeck.setText(null);
        jlblAxle.setText(null);
        jlblWheels.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTax.setText(null);
        jtxtTotal.setText(null);
        Choose_a_deck.setSelectedItem("Make Selection");
        Choose_a_axle.setSelectedItem("Make Selection");
        Choose_a_wheel.setSelectedItem("Make Selection");
        bearingsBox.setSelected(false);
        griptapeBox.setSelected(false);
        riserpadsBox.setSelected(false);
        nutsboltsBox.setSelected(false);
    }//GEN-LAST:event_resetActionPerformed

    private void Choose_a_axleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_a_axleActionPerformed
        // TODO add your handling code here:
        double axle1 = 35;
        double axle2 = 40;
        double axle3 = 45;
        
        if (Choose_a_axle.getSelectedItem().equals("Make Selection"))
        {
            jlblAxle.setText(" ");
        }
        if (Choose_a_axle.getSelectedItem().equals("7.75"))
        {
            String Axle = String.format("%.2f", axle1);
            jlblAxle.setText(Axle);
        }
        if (Choose_a_axle.getSelectedItem().equals("8"))
        {
            String Axle = String.format("%.2f", axle2);
            jlblAxle.setText(Axle);
        }
        if (Choose_a_axle.getSelectedItem().equals("8.5"))
        {
            String Axle = String.format("%.2f", axle3);
            jlblAxle.setText(Axle);
        }
    }//GEN-LAST:event_Choose_a_axleActionPerformed

    private void Choose_a_wheelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_a_wheelActionPerformed
        // TODO add your handling code here:
        double wheel1 = 20;
        double wheel2 = 22;
        double wheel3 = 24;
        double wheel4 = 28;
        
        if (Choose_a_wheel.getSelectedItem().equals("Make Selection"))
        {
            jlblWheels.setText(" ");
        }
        if (Choose_a_wheel.getSelectedItem().equals("51"))
        {
            String Wheel = String.format("%.2f", wheel1);
            jlblWheels.setText(Wheel);
        }
        if (Choose_a_wheel.getSelectedItem().equals("55"))
        {
            String Wheel = String.format("%.2f", wheel2);
            jlblWheels.setText(Wheel);
        }
        if (Choose_a_wheel.getSelectedItem().equals("58"))
        {
            String Wheel = String.format("%.2f", wheel3);
            jlblWheels.setText(Wheel);
        }
        if (Choose_a_wheel.getSelectedItem().equals("61"))
        {
            String Wheel = String.format("%.2f", wheel4);
            jlblWheels.setText(Wheel);
        }
    }//GEN-LAST:event_Choose_a_wheelActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkateboardDesignerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkateboardDesignerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkateboardDesignerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkateboardDesignerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SkateboardDesignerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Choose_a_axle;
    public javax.swing.JComboBox<String> Choose_a_deck;
    public javax.swing.JComboBox<String> Choose_a_wheel;
    public javax.swing.JCheckBox bearingsBox;
    public javax.swing.JButton calculate;
    public javax.swing.JButton exit;
    public javax.swing.JCheckBox griptapeBox;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JLabel jlblAxle;
    public javax.swing.JLabel jlblDeck;
    public javax.swing.JLabel jlblWheels;
    public javax.swing.JTextField jtxtSubTotal;
    public javax.swing.JTextField jtxtTax;
    public javax.swing.JTextField jtxtTotal;
    public javax.swing.JCheckBox nutsboltsBox;
    public javax.swing.JButton reset;
    public javax.swing.JCheckBox riserpadsBox;
    // End of variables declaration//GEN-END:variables
}
