
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author marlon
 */
public class SkateboardGUI extends javax.swing.JFrame {

 /**
     * Creates new form SkateboardGUI
     */
    double [] i = new double [4];
    
    public SkateboardGUI() {
        initComponents();
        
        //fill Deck combo box
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        wheelCombo = new javax.swing.JComboBox<>();
        deckCombo = new javax.swing.JComboBox<>();
        axleCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        subtotal3 = new javax.swing.JLabel();
        subtotal6 = new javax.swing.JLabel();
        subtotal7 = new javax.swing.JLabel();
        nutsBoltsRadio = new javax.swing.JRadioButton();
        bearingsRadio = new javax.swing.JRadioButton();
        gripTapeRadio = new javax.swing.JRadioButton();
        riserPadsRadio = new javax.swing.JRadioButton();
        Jlbl_Axle = new javax.swing.JLabel();
        Jlbl_Decks = new javax.swing.JLabel();
        Jlbl_Wheels = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        totalTF = new javax.swing.JLabel();
        subtotal1 = new javax.swing.JLabel();
        taxTF = new javax.swing.JLabel();
        subtotal4 = new javax.swing.JLabel();
        subtotal5 = new javax.swing.JLabel();
        subtotalTF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 90)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Skate Shop ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1260, 150));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wheelCombo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        wheelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make Selection", "51", "55", "58", "61" }));
        wheelCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wheelComboActionPerformed(evt);
            }
        });
        jPanel3.add(wheelCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 270, 60));

        deckCombo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        deckCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make Selection", "Master Trasher", "Dictator ", "Street King " }));
        deckCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deckComboActionPerformed(evt);
            }
        });
        jPanel3.add(deckCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 280, 60));

        axleCombo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        axleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make Selection", "7.75", "8", "8.5" }));
        axleCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axleComboActionPerformed(evt);
            }
        });
        jPanel3.add(axleCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 270, 60));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Additional add-ons");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 720, -1));

        subtotal3.setBackground(new java.awt.Color(255, 255, 255));
        subtotal3.setFont(new java.awt.Font("Apple Braille", 0, 36)); // NOI18N
        subtotal3.setForeground(new java.awt.Color(0, 0, 0));
        subtotal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtotal3.setText("Wheels:");
        jPanel3.add(subtotal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 200, 60));

        subtotal6.setBackground(new java.awt.Color(255, 255, 255));
        subtotal6.setFont(new java.awt.Font("Apple Braille", 0, 36)); // NOI18N
        subtotal6.setForeground(new java.awt.Color(0, 0, 0));
        subtotal6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtotal6.setText("Decks:");
        jPanel3.add(subtotal6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, 60));

        subtotal7.setBackground(new java.awt.Color(255, 255, 255));
        subtotal7.setFont(new java.awt.Font("Apple Braille", 0, 36)); // NOI18N
        subtotal7.setForeground(new java.awt.Color(0, 0, 0));
        subtotal7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtotal7.setText("Axle:");
        jPanel3.add(subtotal7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 200, 60));

        nutsBoltsRadio.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        nutsBoltsRadio.setForeground(new java.awt.Color(0, 0, 0));
        nutsBoltsRadio.setText("Nuts & Bolts $3");
        nutsBoltsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutsBoltsRadioActionPerformed(evt);
            }
        });
        jPanel3.add(nutsBoltsRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 280, -1, -1));

        bearingsRadio.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        bearingsRadio.setForeground(new java.awt.Color(0, 0, 0));
        bearingsRadio.setText("Bearings $30");
        bearingsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bearingsRadioActionPerformed(evt);
            }
        });
        jPanel3.add(bearingsRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        gripTapeRadio.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        gripTapeRadio.setForeground(new java.awt.Color(0, 0, 0));
        gripTapeRadio.setText("Grip Tape $10");
        gripTapeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gripTapeRadioActionPerformed(evt);
            }
        });
        jPanel3.add(gripTapeRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        riserPadsRadio.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        riserPadsRadio.setForeground(new java.awt.Color(0, 0, 0));
        riserPadsRadio.setText("Riser Pads $2");
        riserPadsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riserPadsRadioActionPerformed(evt);
            }
        });
        jPanel3.add(riserPadsRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, -1, -1));

        Jlbl_Axle.setBackground(new java.awt.Color(255, 255, 255));
        Jlbl_Axle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Jlbl_Axle.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Axle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Jlbl_Axle.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Jlbl_AxleAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(Jlbl_Axle, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 100, 60));

        Jlbl_Decks.setBackground(new java.awt.Color(255, 255, 255));
        Jlbl_Decks.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Jlbl_Decks.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Decks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Jlbl_Decks.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Jlbl_DecksAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(Jlbl_Decks, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 100, 60));

        Jlbl_Wheels.setBackground(new java.awt.Color(255, 255, 255));
        Jlbl_Wheels.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Jlbl_Wheels.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Wheels.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Jlbl_Wheels.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Jlbl_WheelsAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(Jlbl_Wheels, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 100, 100, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1250, 320));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Apple Braille", 0, 48)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel4.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 430, 70));

        calculate.setFont(new java.awt.Font("Apple Braille", 0, 48)); // NOI18N
        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        jPanel4.add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 430, 70));

        totalTF.setBackground(new java.awt.Color(255, 255, 255));
        totalTF.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        totalTF.setForeground(new java.awt.Color(0, 0, 0));
        totalTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(totalTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 250, 40));

        subtotal1.setBackground(new java.awt.Color(255, 255, 255));
        subtotal1.setFont(new java.awt.Font("Apple Braille", 0, 36)); // NOI18N
        subtotal1.setForeground(new java.awt.Color(0, 0, 0));
        subtotal1.setText("Total:");
        jPanel4.add(subtotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 40));

        taxTF.setBackground(new java.awt.Color(255, 255, 255));
        taxTF.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        taxTF.setForeground(new java.awt.Color(0, 0, 0));
        taxTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(taxTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 250, 40));

        subtotal4.setBackground(new java.awt.Color(255, 255, 255));
        subtotal4.setFont(new java.awt.Font("Apple Braille", 0, 36)); // NOI18N
        subtotal4.setForeground(new java.awt.Color(0, 0, 0));
        subtotal4.setText("Tax:");
        jPanel4.add(subtotal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 40));

        subtotal5.setBackground(new java.awt.Color(255, 255, 255));
        subtotal5.setFont(new java.awt.Font("Apple Braille", 0, 36)); // NOI18N
        subtotal5.setForeground(new java.awt.Color(0, 0, 0));
        subtotal5.setText("Subtotal:");
        jPanel4.add(subtotal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 40));

        subtotalTF.setBackground(new java.awt.Color(255, 255, 255));
        subtotalTF.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        subtotalTF.setForeground(new java.awt.Color(0, 0, 0));
        subtotalTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        subtotalTF.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                subtotalTFAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.add(subtotalTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 250, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 1260, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Skateboard Designer", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void deckComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deckComboActionPerformed
        // TODO add your handling code here:  
        double trasher = 60;
        double dictator = 45;
        double king = 50;
        
        if (deckCombo.getSelectedItem().equals("Make Selection"))
        {
            Jlbl_Decks.setText(" ");
        }
        if (deckCombo.getSelectedItem().equals("Master Trasher"))
        {
            String Deck = String.format("%.2f", trasher);
            Jlbl_Decks.setText(Deck);
        }
        if (deckCombo.getSelectedItem().equals("Dictator"))
        {
            String Deck = String.format("%.2f", dictator);
            Jlbl_Decks.setText(Deck);
        }
        if (deckCombo.getSelectedItem().equals("Street King"))
        {
            String Deck = String.format("%.2f", king);
            Jlbl_Decks.setText(Deck);
        }
        
    }//GEN-LAST:event_deckComboActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:  
        double bearings = 30;
        double gripTape = 10;
        double riserPad = 2;
        double nutsBolts = 3;
        
        double AddAll;
        double iTax = 7;
        double Tax;
        double Choose_Deck = Double.parseDouble(Jlbl_Decks.getText());
        double Choose_Axle = Double.parseDouble(Jlbl_Axle.getText());
        double Choose_Wheels = Double.parseDouble(Jlbl_Wheels.getText());
        
        subtotalTF.setText("");
        totalTF.setText("");
        
        if (bearingsRadio.isSelected() && gripTapeRadio.isSelected() && riserPadsRadio.isSelected() && nutsBoltsRadio.isSelected())
            {
                i[0] = bearings; 
                i[1] = gripTape;
                i[2] = riserPad;
                i[3] = nutsBolts;
                
                if (deckCombo.getSelectedItem().equals("Master Trasher") && (axleCombo.getSelectedItem().equals("7.75")) 
                    && wheelCombo.getSelectedItem().equals("51"));
                {
                    Choose_Deck  = Choose_Deck + Choose_Axle + Choose_Wheels;
                    AddAll = Choose_Deck + i[0] + i[1] + i[2] + i[3];
                    
                    Tax = (AddAll * iTax/100);
                    String sTax = String.format("$ %.2f", Tax);
                     taxTF.setText(sTax);
                    
                    String SubTotal = String.format("$ %.2f", AddAll);
                    subtotalTF.setText(SubTotal);
                    
                    String Total = String.format("$ %.2f", AddAll + Tax);
                    totalTF.setText(Total);
                    
                    }
                }
        else
            {
                AddAll = Choose_Deck + Choose_Axle + Choose_Wheels;
                String Total = String.format("$ %.2f", AddAll);
                subtotalTF.setText(Total);
                totalTF.setText(Total);
                }
        //==========/=============
        
        
    /*
        
        if (bearingsRadio.isSelected())
        {
            i[0] = bearings;
        }
        else 
        {
            i[0] = (0);
        }
        
        if (gripTapeRadio.isSelected())
        {
            i[1] = gripTape;
        }
        else 
        {
            i[1] = (0);
        }
        
         if (riserPadsRadio.isSelected())
        {
            i[2] = riserPad;
        }
        else 
        {
            i[2] = (0);
        }
        
        if (nutsBoltsRadio.isSelected())
        {
            i[3] = nutsBolts;
        }
        else 
        {
            i[3] = (0);
        }
        
        AddAll = i[0] +i[1] +i[2] +i[3];
        String Total = String.format("%.2f", AddAll);
        totalTF.setText(Total); */
        
    }//GEN-LAST:event_calculateActionPerformed

    private void Jlbl_AxleAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Jlbl_AxleAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Jlbl_AxleAncestorAdded

    private void gripTapeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gripTapeRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gripTapeRadioActionPerformed

    private void nutsBoltsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutsBoltsRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nutsBoltsRadioActionPerformed

    private void riserPadsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riserPadsRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riserPadsRadioActionPerformed

    private void bearingsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bearingsRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bearingsRadioActionPerformed

    private void axleComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axleComboActionPerformed
        // TODO add your handling code here:
        double axle775 = 35;
        double axle8 = 40;
        double axle85 = 45;
        
        if (axleCombo.getSelectedItem().equals("Make Selection"))
        {
            Jlbl_Axle.setText(" ");
        }
        
        if (axleCombo.getSelectedItem().equals("7.75"))
        {
            String Axle = String.format("%.2f", axle775);
            Jlbl_Axle.setText(Axle);
        }
        
        if (axleCombo.getSelectedItem().equals("8"))
        {
            String Axle = String.format("%.2f", axle8);
            Jlbl_Axle.setText(Axle);
        }
        
        if (axleCombo.getSelectedItem().equals("8.5"))
        {
            String Axle = String.format("%.2f", axle85);
            Jlbl_Axle.setText(Axle);
        }
                
    
        
    }//GEN-LAST:event_axleComboActionPerformed

    private void subtotalTFAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_subtotalTFAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalTFAncestorAdded

    private void Jlbl_DecksAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Jlbl_DecksAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Jlbl_DecksAncestorAdded

    private void Jlbl_WheelsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Jlbl_WheelsAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Jlbl_WheelsAncestorAdded

    private void wheelComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheelComboActionPerformed
        // TODO add your handling code here:
        double wheel51 = 20;
        double wheel55= 22;
        double wheel58 = 24;
        double wheel61 =28;
        
        if (wheelCombo.getSelectedItem().equals("Make Selection"))
        {
            Jlbl_Wheels.setText(" ");
        }
        
        if (wheelCombo.getSelectedItem().equals("51"))
        {
            String Wheel = String.format("%.2f", wheel51);
            Jlbl_Wheels.setText(Wheel);
        }
        
        if (wheelCombo.getSelectedItem().equals("55"))
        {
            String Wheel = String.format("%.2f", wheel55);
            Jlbl_Wheels.setText(Wheel);
        }
        
        if (wheelCombo.getSelectedItem().equals("58"))
        {
            String Wheel = String.format("%.2f", wheel58);
            Jlbl_Wheels.setText(Wheel);
        }
        
        if (wheelCombo.getSelectedItem().equals("61"))
        {
            String Wheel = String.format("%.2f", wheel61);
            Jlbl_Wheels.setText(Wheel);
        }
    }//GEN-LAST:event_wheelComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkateboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkateboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkateboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkateboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SkateboardGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Jlbl_Axle;
    public javax.swing.JLabel Jlbl_Decks;
    public javax.swing.JLabel Jlbl_Wheels;
    public javax.swing.JComboBox<String> axleCombo;
    public javax.swing.JRadioButton bearingsRadio;
    public javax.swing.JButton calculate;
    public javax.swing.JComboBox<String> deckCombo;
    public javax.swing.JButton exit;
    public javax.swing.JRadioButton gripTapeRadio;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JRadioButton nutsBoltsRadio;
    public javax.swing.JRadioButton riserPadsRadio;
    public javax.swing.JLabel subtotal1;
    public javax.swing.JLabel subtotal3;
    public javax.swing.JLabel subtotal4;
    public javax.swing.JLabel subtotal5;
    public javax.swing.JLabel subtotal6;
    public javax.swing.JLabel subtotal7;
    public javax.swing.JLabel subtotalTF;
    public javax.swing.JLabel taxTF;
    public javax.swing.JLabel totalTF;
    public javax.swing.JComboBox<String> wheelCombo;
    // End of variables declaration//GEN-END:variables
}
